seed: 0
use_vr: false
data_path: calvin_env_modified/assets/data
save_dir: /tmp
record: false

hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - _self_
  - cameras: wrist_and_front
  #- vr_input: None
  - env: master_env
  - scene: master_playtable
  - robot: master_eval
  - tasks: master_tasks
  - recorder: recorder
  #- override hydra/job_logging: colorlog
  #- override hydra/hydra_logging: colorlog
