_target_: calvin_env.scene.master_scene.Scene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [-0.34, -0.46, 0.24]
robot_base_orientation: [0, 0, 0]
robot_initial_joint_positions:
  [
    -1.21779206,
    1.03987646,
    2.11978261,
    -2.34205014,
    -0.87015947,
    1.64119353,
    0.55344866,
  ]
surfaces:
  table: [[0.0, -0.15, 0.46], [0.30, -0.03, 0.46]]
  #slider_left: [[-0.32, 0.05, 0.46], [-0.16, 0.12, 0.46]]
  #slider_right: [[-0.05, 0.05, 0.46], [0.13, 0.12, 0.46]]
  drawer_open: [[0.04, -0.35, 0.38], [0.30, -0.21, 0.38]]
  drawer_closed: [[0.04, -0.16, 0.38], [0.30, -0.03, 0.38]]
objects:
  fixed_objects:
    table:
      file: calvin_table_D/urdf/calvin_table_D.urdf
      initial_pos: [0, 0, 0]
      initial_orn: [0, 0, 0]
      joints:
        base__slide:
          link: slide_link
          initial_state: any # Prismatic
        base__drawer:
          link: drawer_link
          initial_state: any # Prismatic
      buttons:
        base__button:
          link: button_link
          initial_state: 0 # Prismatic
          effect: led
      switches:
        base__switch:
          link: switch_link
          initial_state: any # Revolute
          effect: lightbulb
      lights:
        lightbulb:
          link: light_link
          initial_state: any
          color: [0, 1, 0, 1] # pink
        led:
          link: led_link
          initial_state: any
          color: [0, 1, 0, 1] # green
  movable_objects:
    block_red:
      file: blocks/block_red_middle.urdf
      initial_pos: any
      initial_orn: [0, 0, 1.5708]
    block_blue:
      file: blocks/block_blue_small.urdf
      initial_pos: any
      initial_orn: [0, 0, 0]
    block_pink:
      file: blocks/block_pink_big.urdf
      initial_pos: any
      initial_orn: [0, 0, 1.5708]
