seed: 40
use_vr: false
data_path: data
save_dir: /tmp
record: true
bullet_time_step: 80.0

hydra:
  run:
    dir: ${save_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}

defaults:
  - cameras: static_and_gripper
  - vr_input: vr_input
  - env: play_table_env_tapas
  - scene: basic_tapas_playtable
  - robot: panda_longer_finger
  - tasks: new_playtable_tasks
  - recorder: recorder
  #- override hydra/job_logging: colorlog
  #- override hydra/hydra_logging: colorlog
